version: 2
updates:

  - package-ecosystem: "github-actions"
    directories: 
      - "/"
      - "/.github/actions/wsusoffline/"
    schedule:
      interval: "weekly"
      day: saturday
      time: "09:00"
